### ISSUE TITLE
¿how can i modify verify function to use my local node?

### ISSUE THREAD

**Issue by FSBalbuena** [opentimestamps/javascript-opentimestamps#26]
i have use this project on my site but now i want to verify my files with a local bitcoin node.
is there a native way to edit verify function in order to verify on my node?
if is not, i am thinking of using node-cmd to control my comand line. 
hope you can give me a hand with this.

**Comment by RCasatta** [comment]
The client looks for the `bitcoin.conf` file in default places according to your OS
`const list = ['/.bitcoin/bitcoin.conf', '\\AppData\\Roaming\\Bitcoin\\bitcoin.conf', '/Library/Application Support/Bitcoin/bitcoin.conf']`
Do you have this file in a standard place? Does it contain valid values for rpcuser, rpcpassword, rpcconnect and rpcport?

**Comment by FSBalbuena** [comment]
RCasatta, you're right But I think I did not explain correctly.
I'm using javascript-opentimestamps now. I can verify even if I do not have a local node, because it does it directly to the OpenTimeStamp service.
says in the documentation "Note: This verification using block explorers is convenient but not as secure as asking a local node..."
What I wanted to know is if I can rewrite the verification method in the library to use it with a local node. That way I can preserve the code on my page and everything will continue to work.

**Comment by lvaccaro** [comment]
Hi @FSBalbuena, javascript-opentimestamps support two different verification methods (see [verifyAttestation function](https://github.com/opentimestamps/javascript-opentimestamps/blob/11e4205edef588317dffa629e4a4f7b0d43c0f30/src/open-timestamps.js#L341))
- [liteVerify](https://github.com/opentimestamps/javascript-opentimestamps/blob/11e4205edef588317dffa629e4a4f7b0d43c0f30/src/open-timestamps.js#L343) with block explorer, you mention before
- bitcoin node verification: you can check the [reference code](https://github.com/opentimestamps/javascript-opentimestamps/blob/11e4205edef588317dffa629e4a4f7b0d43c0f30/src/open-timestamps.js#L383) on verifyAttestation function
```js
// Check for local bitcoin configuration
Bitcoin.BitcoinNode.readBitcoinConf().then(properties => {
...
```
Note: `readBitcoinConf()` use default places according to your OS (as described by @RCasatta) to read bitcoin rpc properities.

Moreover, javascript-opentimestamps always try to use bitcoin node verification first. If this process fails (because there are no bitcoin.conf file, bitcoin node is down, so on..), the library makes a lite verification with block explorers.

**Comment by FSBalbuena** [comment]
Yeah guys, thank you very much!
This are great News!
I really appreciate the time and the willingness you had had to answer this question

**Comment by RCasatta** [comment]
We updated the readme trying to avoid misunderstanding.
https://github.com/opentimestamps/javascript-opentimestamps/commit/84379438eb8cec0b01e58078778eb1efd42e77ef
