### ISSUE TITLE
Catallaxy server not showing up?

### ISSUE THREAD

**Issue by FrancisPouliot** [opentimestamps/javascript-opentimestamps#52]
I wonder if there is a problem with Catallaxy server because it's not showing up on the opentimestamps.org page. 

Also, curios what is this value: https://github.com/opentimestamps/javascript-opentimestamps/blob/9992ab136b974410e43cd7237f6f57522358bb95/test/timestamp.js#L197

**Comment by petertodd** [comment]
Ah, yeah, you mean that the timestamper on that page isn't using Catallaxy? I can confirm that's not working on my machine either.

Otherwise the Catallaxy server seems to work just fine - I haven't noticed any timestamps on my system not using it.

Maybe open an issue on https://github.com/opentimestamps/opentimestamps.org ?

**Comment by FrancisPouliot** [comment]
Yeah I can close this here and open on the other repo thanks!
